version: "3.9"

services:
  legendary-db:
    image: postgres:14
    container_name: legendary-db
    environment:
      POSTGRES_DB: "legendarydb"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
    command: ["postgres", "-c", "listen_addresses=*"]
    mem_limit: 2048m
    ports:
      - 5432:5432
    volumes:
      - ./Postgres:/docker-entrypoint-initdb.d # Инициализация таблиц
      - ./volumes/Database/data:/var/lib/postgresql/data # Папка, где postgres будет хранить данные
      - ./volumes/Database/backups:/backups # Папка для бекапов
    networks:
      - legendary-network
  legendary-api:
    image: legendary-api-image
    build:
      context: ./src/LegendarySocialNetwork
      dockerfile: Dockerfile
    container_name: legendary-api
    restart: always
    environment:
      # Основные настройки для работы API
      ASPNETCORE_URLS: "http://+:80"
      AllowedHosts: "*" # Ограничивает хосты, которые могут подключаться к API. По умолчанию - все
      # Строка подключения к базе данных Postgres
      DatabaseSettings:ConnStr: "Host=legendary-db;Port=5432;Username=dbuser;Password=dbpassword;Database=legendarydb;Pooling=true;Maximum Pool Size=950;Minimum Pool Size=200;Timeout=300;CommandTimeout=300;Connection Idle Lifetime=300;Connection Pruning Interval=10;Keepalive=60;TCP Keepalive Time=60;TCP Keepalive Interval=10"
      JWTSettings:Key: "superSecretKey@34512312312312312"
      JWTSettings:Issuer: legendary.social.network
      JWTSettings:Audience: legendary.social.network
      JWTSettings:DurationInMinutes: "60"
    ports:
      - 7888:80
    mem_limit: 1024m
    entrypoint: dotnet LegendarySocialNetwork.dll
    depends_on:
      - legendary-db
    networks:
      - legendary-network
  legendary-react-app:
    build:
      context: ./legendary-client  # Update this to the path where your React app is located
      dockerfile: Dockerfile  # Make sure you have a Dockerfile in this directory for your React app
    container_name: legendary-react-app
    ports:
      - 3000:80  # Map port 3000 on the host to port 80 in the container
    networks:
      - legendary-network    
networks:
  legendary-network:
    driver: bridge

