version: "3.9"

services:
  legendary-db:
    image: postgres:14
    container_name: legendary-db
    environment:
      POSTGRES_DB: "legendarydb"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "dbpassword"
    mem_limit: 512m
    ports:
      - 5432:5432
    volumes:
      - ./Postgres:/docker-entrypoint-initdb.d # Инициализация таблиц
      - ./volumes/Database/data:/var/lib/postgresql/data # Папка, где postgres будет хранить данные
      - ./volumes/Database/backups:/backups # Папка для бекапов
    networks:
      - legendary-network
  legendary-api:
    image: legendary-api-image
    build:
      context: ./src/LegendarySocialNetwork
      dockerfile: Dockerfile
    container_name: legendary-api
    restart: always
    environment:
      # Основные настройки для работы API
      ASPNETCORE_URLS: "http://+:80"
      AllowedHosts: "*" # Ограничивает хосты, которые могут подключаться к API. По умолчанию - все
      # Строка подключения к базе данных Postgres
      DatabaseSettings:ConnStr: "Host=legendary-db;Port=5432;Username=dbuser;Password=dbpassword;Database=legendarydb;Pooling=true;"
      # Настройки генерации токена авторизации
      JWTSettings:Key: "superSecretKey@34512312312312312"
      JWTSettings:Issuer: legendary.social.network
      JWTSettings:Audience: legendary.social.network
      JWTSettings:DurationInMinutes: "60"
    ports:
      - 7888:80
    mem_limit: 1024m
    entrypoint: dotnet LegendarySocialNetwork.dll
    depends_on:
      - legendary-db
    networks:
      - legendary-network
networks:
  legendary-network:
    driver: bridge

